#!/bin/bash

DIR=./opencaster-3.2.2/tools
TMP=/tmp
LOOP=$DIR/tsloop/tsloop
UDPSEND=$DIR/tsudpsend/tsudpsend
BITRATE=${1:-2049952}
FILE=./stream.m2t

NUM=5

chmod +x $LOOP
chmod +x $UDPSEND

for (( i=1; i<=$NUM; i++ ))
do
    echo "File $i"
    FIFO=$TMP/fifo$i.ts
    rm $FIFO # remove previously created file, if any
    mkfifo $FIFO
    $LOOP $FILE > $FIFO &
    $UDPSEND $FIFO "224.1.2.$i" 1234 $BITRATE &
done
